---
abstract: 'See Your Data in the Nude'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XXX
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  YAML::PP: '0.018'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/xxx-pm/issues
  homepage: https://github.com/ingydotnet/xxx-pm
  repository: https://github.com/ingydotnet/xxx-pm.git
version: '0.38'
x_generated_by_perl: v5.28.0
x_serialization_backend: 'YAML::Tiny version 1.73'
